name: Daily Update Dependencies

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: main

      - name: Setup toolchains
        uses: ./.github/workflows/setup-toolchains
        with:
          cargo-edit: "true"

      - name: Run update script
        run: |
          chmod +x ./scripts/update_deps.rs && ./scripts/update_deps.rs

      - name: Create or update PR
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          branch: ci/update-deps
          commit-message: "chore: Update deps"
          title: "chore: Update deps"
          body: "Automatic update of dependencies."
          base: main
          delete-branch: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable PR automerge
        run: gh pr merge --squash --auto ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-examples:
    needs: ["update-deps"]
    uses: ./.github/workflows/run_examples.yml

  run-tests:
    needs: ["update-deps"]
    uses: ./.github/workflows/run_tests.yml
