name: Run tests

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: main

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: "rustc-codegen-cranelift"

      - name: Setup nextest
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run --all-features --no-capture --workspace
